### ISSUE TITLE
Working with debug symbols

### ISSUE THREAD

**Issue by ruslo** [ruslo/CGold#17]
- [ ] https://github.com/ruslo/CGold/issues/6 (lldb)
- [ ] https://github.com/ruslo/CGold/issues/7 (gdb)
- [ ] https://github.com/ruslo/CGold/issues/8 (PDB)
